name: Build IPA for SideStore
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - run: flutter pub get
      - name: Pod install
        run: pod install --repo-update
        working-directory: ios
      - run: flutter build ios --release --no-codesign
      - name: Táº¡o IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload && mv Runner.app Payload/
          zip -r9 Flutter.ipa Payload
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: SideStore-IPA
          path: build/ios/iphoneos/Flutter.ipa
